SmartSchedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), 
    path('api/', include('restapi.urls')),
    path('schedule/', include('schedule.urls')), 
    path('account/', include('account.urls')),
]

account/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path("auth/", UserSignInView.as_view(), name="auth"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("logout/", logout_view, name="logout"),
]

main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path("", MainPageView.as_view(), name="main")
]

account/models.py
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    class Roles(models.TextChoices):
        STUDENT = "ST"
        TEACHER = "T"
        OTHER = "O"
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_name = models.CharField(name="last_name", max_length=75)
    name = models.CharField(name="name", max_length=75)
    surname = models.CharField(name="surname", max_length=75)
    phone = models.CharField(name="phone", max_length=20)
    group = models.CharField(name="group", max_length=15, null=True)
    role = models.CharField(name="role", choices=Roles, default=Roles.STUDENT)

    def __str__(self):
        return self.name

class Subjects(models.Model):
    title = models.CharField(name="title", max_length=150)

    def __str__(self):
        return self.title

class StudentsCourse(models.Model):
    title = models.CharField(name="title", max_length=30)
    participants = models.ForeignKey(Profile, on_delete=models.CASCADE)
    subjects = models.ForeignKey(Subjects, on_delete=models.CASCADE, null=True)
    institute = models.CharField(name="institute", max_length=10)

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    email = forms.EmailField(
        widget = forms.EmailInput(
            attrs={"type": "email", "id":"email", "name":"email", "placeholder":"Почта"}
        ),
        label="Почта"
    )
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={"class": "password__input", "type": "password", "id": "password", "name": "password", "placeholder" :"Пароль"} 
        ),
        label="Пароль"
    )

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")

        if email and password:
            user = authenticate(username=email, password=password)
            if user is None:
                raise ValidationError("Неправильная почта или пароль.")
            self.user = user

        return cleaned_data

    def get_user(self):
        return getattr(self, 'user', None)

account/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView, TemplateView
from .forms import LoginForm
from django.urls import reverse_lazy
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile

class UserSignInView(FormView):
    template_name = "authorization.html"
    form_class = LoginForm
    success_url = reverse_lazy("main:main")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("main:main")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.get_user()
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "profile.html"
    login_url = "account:auth"

    def get_object(self):
        return Profile.objects.get(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        profile = Profile.objects.get(user=user)
        context["role"] = profile.role
        context["phone"] = profile.phone
        context["group"] = profile.group
        context["name"] = profile.name
        context["surname"] = profile.surname
        context["last_name"] = profile.last_name
        return context

def logout_view(request):
    logout(request)
    return redirect("account:auth")

account/templates/authorization.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <title>Вход в университет</title>
</head>
<body>
    <div class="container">
        <div class="left-panel">
            <img src="https://img.icons8.com/ios-filled/50/000000/university.png" alt="Иконка университета" class="icon">
            <h1>С возвращением в университет</h1>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn">Войти</button>
            </form>
        </div>
        <div class="right-panel"></div>
    </div>
</body>
</html>

account/templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
    <title>Профиль пользователя</title>
</head>
<body>
    <a href="{% url 'main:main' %}" class="back-btn">Назад</a>
    <div class="profile-container">
        <div class="profile-header">
            <div class="profile-photo">
                <img src="https://i.pinimg.com/originals/a1/7b/36/a17b36ca9f2d47edf2b7186c08350905.jpg" alt="Фото профиля">
            </div>
            <div class="profile-info">
                <h1 class="profile-name">{{ last_name }} {{ name }}</h1>
            </div>
        </div>
        <div class="info-section">
            <h2>Информация о пользователе</h2>
            <div class="info-item">
                <span class="info-label">Почта:</span>
                <span class="info-value">{{ user.email }}</span>
            </div>
            <div class="info-item">
                <span class="info-label">Номер телефона:</span>
                <span class="info-value">{{ phone }}</span>
            </div>
            <div class="info-item">
                {% if role == 'ST' %}
                <span class="info-label">Группа студента:</span>
                <span class="info-value">{{ group }}</span>
                {% else %}
                <span class="info-label">Группы преподавателя:</span>
                <span class="info-value">{{ group }}</span>
                {% endif %}
            </div>
        </div>
        <div class="subjects-section">
        </div>
        <a href="{% url 'account:logout' %}" class="logout-btn">Выйти из аккаунта</a>
    </div>
</body>
</html>