SmartSchedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), 
    path('api/', include('restapi.urls')),
    path('schedule/', include('schedule.urls')), 
    path('account/', include('account.urls')),
]

account/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path("auth/", UserSignInView.as_view(), name="auth"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("logout/", logout_view, name="logout"),
]

main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path("", MainPageView.as_view(), name="main")
]

schedule/urls.py
from django.urls import path
from .views import *

app_name = "schedule"

urlpatterns = [
    path("create/", LessonCreateView.as_view(), name="create_lesson"),
    path("update/<pk>/", LessonUpdateView.as_view(), name="update_lesson"),
    path("delete/<pk>/", LessonDeleteView.as_view(), name="delete_lesson"),
    path("courses/", CourseView.as_view(), name="courses_list"),
    path("create/courses/", CourseCreateView.as_view(), name="create_course"),
    path("notifications/", NotificationView.as_view(), name="notifications_list"),
    path('send-email/', send_notification_view, name='send_email'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView
from account.models import Profile
from datetime import date, timedelta
from django.utils import timezone
from schedule.models import Lessons

class MainPageView(ListView):
    template_name = "main.html"
    model = Lessons
    context_object_name = 'lessons'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("account:auth")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        role = Profile.objects.get(user=self.request.user).role
        lesson_date = Lessons.objects.all()

        lessons = []
        for i in lesson_date:
            lessons.append({
                "id": i.id,
                "year": str(i.date).split()[0],
                "title": i.title,
                "duration": i.duration,
                "classroom": i.classroom,
                "flow": i.flow,
                "comment": i.comment
                })

        today = timezone.now().date()
        week_start = today - timedelta(days=today.weekday())
        
        days_ru = ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье']
        date = []
        for i, day in enumerate(days_ru):
            day_date = week_start + timedelta(days=i)
            date.append({
                "day": day,
                "date" : day_date,
                "date_str": day_date.strftime("%Y-%m-%d")
            })

        context["lessons"] = lessons
        context["role"] = role
        context["date"] = date

        return context

main/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Умное расписание курсов</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
<header>
    <div class="header-left">
        <h1>Ваши занятия</h1>
        <a href="{% url 'main:main' %}" class="nowbar1">Главная</a>
        <a href="{% url 'schedule:courses_list' %}" class="nowbar2">Курсы</a>
        <div class="nowbar3">Расписание</div>
    </div>
    <div class="header-right">
        {% if role == 'T' %}
        <a href="{% url 'schedule:create_lesson' %}" class="add-event-btn">Добавить событие</a>
        {% endif %}
        <div class="notifications">
            <a href="{% url 'schedule:notifications_list' %}"><img
                    src="https://img.icons8.com/?size=100&id=LaPTWTgsJCs1&format=png&color=FFFFFF" alt="Уведомления"
                    width="24" height="24"></a>
        </div>
        <div class="profile">
            {% if request.user %}
            <a href="{% url 'account:profile' %}" class="avatar"></a>
            {% else %}
            <a href="{% url 'account:auth' %}">Авторизоваться</a>
            {% endif %}
        </div>
    </div>
</header>
<main>
    <section class="calendar">
        <h2>Календарь на неделю</h2>
        <div class="week">
            {% for day in date %}
            <div class="day" data-day="{{ day.date_str }}">
                <h3>{{ day.day }}</h3>
                <p>{{ day.date }}</p>
            </div>
            {% endfor %}
        </div>
    </section>
    <section class="subjects">
        {% for lesson in lessons %}
        <div class="subject-card show" data-days="{{ lesson.year }}">
            <h3>{{ lesson.title }}</h3>
            <p><strong>Продолжительность:</strong> {{ lesson.duration }} </p>
            <p><strong>Преподаватель:</strong></p>
            <p><strong>Аудитория:</strong> {{ lesson.classroom }} </p>
            <p><strong>Направление:</strong> {{ lesson.flow }}</p>
            {% if lesson.comment != "" %}
            <p><strong>Комментарий преподавателя:</strong> {{ lesson.comment }}</p>
            {% endif %}
            {% if role == 'T' %}
            <a href="{% url 'schedule:update_lesson' lesson.id %}" class="edit-lesson-btn">Редактировать</a>
            <a href="{% url 'schedule:delete_lesson' lesson.id %}" class="delete-lesson-btn">Удалить</a>
            {% endif %}
        </div>
        {% endfor %}
    </section>
</main>

<script>
    const days = document.querySelectorAll('.day');
    const subjectCards = document.querySelectorAll('.subject-card');

    days.forEach(day => {
        day.addEventListener('click', () => {
            // Убрать активный класс со всех дней
            days.forEach(d => d.classList.remove('active'));
            // Добавить активный класс к выбранному дню
            day.classList.add('active');

            const selectedDay = day.getAttribute('data-day');

            // Скрыть все карточки
            subjectCards.forEach(card => {
                card.classList.remove('show');
            });

            // Показать карточки для выбранного дня
            subjectCards.forEach(card => {
                if (card.getAttribute('data-days') === selectedDay) {
                    card.classList.add('show');
                }
            });
        });
    });
</script>
</body>

</html>